apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: a8qjxsniy-go 
  janus-idp.io/tekton: a8qjxsniy-go
  backstage.io/kubernetes-id: a8qjxsniy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a8qjxsniy-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml